// src/utils/constants.js
export const TOOLS = [
  { id: 'home', name: 'DNS Propagation Checker', path: '/', icon: '🌍', category: 'DNS Tools', description: 'Check DNS propagation across global servers' },
  { id: 'dns-lookup', name: 'DNS Lookup', path: '/dns-lookup', icon: '🔍', category: 'DNS Tools', description: 'Look up DNS records for any domain' },
  { id: 'reverse-dns', name: 'Reverse DNS', path: '/reverse-dns', icon: '🔄', category: 'DNS Tools', description: 'Find hostname from IP address' },
  { id: 'dns-compare', name: 'DNS Compare', path: '/dns-compare', icon: '⚖️', category: 'DNS Tools', description: 'Compare DNS records between two domains' },
  { id: 'dnssec-check', name: 'DNSSEC Checker', path: '/dnssec-check', icon: '🛡️', category: 'DNS Tools', description: 'Verify DNSSEC configuration' },
  { id: 'ns-lookup', name: 'NS Lookup', path: '/ns-lookup', icon: '📡', category: 'DNS Tools', description: 'Look up nameservers' },
  { id: 'mx-lookup', name: 'MX Lookup', path: '/mx-lookup', icon: '📧', category: 'DNS Tools', description: 'Look up mail server records' },
  { id: 'txt-lookup', name: 'TXT Lookup', path: '/txt-lookup', icon: '📝', category: 'DNS Tools', description: 'Look up TXT, SPF, DKIM, DMARC records' },
  { id: 'public-dns', name: 'Public DNS List', path: '/public-dns', icon: '📋', category: 'DNS Tools', description: 'Browse public DNS servers worldwide' },
  { id: 'whois', name: 'WHOIS Lookup', path: '/whois', icon: '🏢', category: 'Domain Intelligence', description: 'Domain registration information' },
  { id: 'domain-age', name: 'Domain Age', path: '/domain-age', icon: '📅', category: 'Domain Intelligence', description: 'Check domain age and dates' },
  { id: 'ip-geolocation', name: 'IP Geolocation', path: '/ip-geolocation', icon: '📍', category: 'Domain Intelligence', description: 'Find IP address location' },
  { id: 'asn-lookup', name: 'ASN Lookup', path: '/asn-lookup', icon: '🏗️', category: 'Domain Intelligence', description: 'Autonomous System Number info' },
  { id: 'ip-to-domain', name: 'IP to Domain', path: '/ip-to-domain', icon: '🔗', category: 'Domain Intelligence', description: 'Find domains on an IP' },
  { id: 'http-headers', name: 'HTTP Headers', path: '/http-headers', icon: '📋', category: 'Network Tools', description: 'Check HTTP response headers' },
  { id: 'ssl-checker', name: 'SSL Checker', path: '/ssl-checker', icon: '🔒', category: 'Network Tools', description: 'Verify SSL/TLS certificate' },
  { id: 'website-status', name: 'Website Status', path: '/website-status', icon: '🟢', category: 'Network Tools', description: 'Check if website is up or down' },
  { id: 'my-ip', name: 'What is My IP', path: '/my-ip', icon: '🌐', category: 'Network Tools', description: 'Find your public IP address and location' },
  { id: 'spf-dmarc', name: 'SPF & DMARC Validator', path: '/spf-dmarc', icon: '✉️', category: 'DNS Tools', description: 'Validate SPF and DMARC email authentication' },
  { id: 'domain-health', name: 'Domain Health Score', path: '/domain-health', icon: '💯', category: 'Domain Intelligence', description: 'Comprehensive domain health grade (A-F)' },
  { id: 'password-generator', name: 'Password Generator', path: '/password-generator', icon: '🔑', category: 'Utility Tools', description: 'Generate strong random passwords' },
  { id: '2fa', name: '2FA Generator', path: '/2fa', icon: '⏱️', category: 'Utility Tools', description: 'Generate Time-based OTPs from secrets' },
  { id: 'base64', name: 'Base64 Encode/Decode', path: '/base64', icon: '🔤', category: 'Utility Tools', description: 'Encode or decode Base64 strings' },
  { id: 'url-encode', name: 'URL Encode/Decode', path: '/url-encode', icon: '🔗', category: 'Utility Tools', description: 'Encode or decode URL strings' },
  { id: 'json-formatter', name: 'JSON Formatter', path: '/json-formatter', icon: '📐', category: 'Utility Tools', description: 'Format, validate, and minify JSON' },
  { id: 'regex-tester', name: 'Regex Tester', path: '/regex-tester', icon: '🧩', category: 'Utility Tools', description: 'Test and debug regular expressions in real-time' },
  { id: 'jwt-decoder', name: 'JWT Decoder', path: '/jwt-decoder', icon: '🔓', category: 'Utility Tools', description: 'Decode and inspect JSON Web Tokens' },
  { id: 'hash-generator', name: 'Hash Generator', path: '/hash-generator', icon: '#️⃣', category: 'Utility Tools', description: 'Generate MD5, SHA-1, SHA-256, SHA-512 hashes' },
  { id: 'uuid-generator', name: 'UUID Generator', path: '/uuid-generator', icon: '🆔', category: 'Utility Tools', description: 'Generate and validate UUIDs (v4)' },
  { id: 'timestamp', name: 'Unix Timestamp', path: '/timestamp', icon: '⏰', category: 'Utility Tools', description: 'Convert between Unix timestamps and dates' },
  { id: 'mac-lookup', name: 'MAC Address Lookup', path: '/mac-lookup', icon: '💻', category: 'Network Tools', description: 'Find device manufacturer (OUI) by MAC Address' },
  { id: 'subnet-calc', name: 'IP Subnet Calculator', path: '/subnet-calc', icon: '🧮', category: 'Network Tools', description: 'Calculate IP ranges, networks, and broadcast addresses' },
  { id: 'port-scanner', name: 'Port Scanner', path: '/port-scanner', icon: '🚪', category: 'Network Tools', description: 'Scan public IP/Domain for open network ports' },
];

export const RECORD_TYPES = [
  { value: 'A', label: 'A' },
  { value: 'AAAA', label: 'AAAA' },
  { value: 'CNAME', label: 'CNAME' },
  { value: 'MX', label: 'MX' },
  { value: 'NS', label: 'NS' },
  { value: 'TXT', label: 'TXT' },
  { value: 'SOA', label: 'SOA' },
  { value: 'PTR', label: 'PTR' },
  { value: 'SRV', label: 'SRV' },
  { value: 'CAA', label: 'CAA' },
];
